// Code generated by moshi-kotlin-codegen. Do not edit.
package de.michaelpohl.loopy.ui.licenses

import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import com.squareup.moshi.Moshi
import com.squareup.moshi.internal.Util
import java.lang.NullPointerException
import java.lang.reflect.Constructor
import kotlin.Int
import kotlin.String
import kotlin.Suppress
import kotlin.collections.emptySet
import kotlin.jvm.Volatile
import kotlin.text.buildString

@Suppress("DEPRECATION", "unused", "ClassName", "REDUNDANT_PROJECTION")
class Libraries_Library_ArtifactIdJsonAdapter(
  moshi: Moshi
) : JsonAdapter<Libraries.Library.ArtifactId>() {
  private val options: JsonReader.Options = JsonReader.Options.of("name", "group", "version")

  private val nullableStringAdapter: JsonAdapter<String?> = moshi.adapter(String::class.java,
      emptySet(), "name")

  @Volatile
  private var constructorRef: Constructor<Libraries.Library.ArtifactId>? = null

  override fun toString(): String = buildString(50) {
      append("GeneratedJsonAdapter(").append("Libraries.Library.ArtifactId").append(')') }

  override fun fromJson(reader: JsonReader): Libraries.Library.ArtifactId {
    var name: String? = null
    var group: String? = null
    var version: String? = null
    var mask0 = -1
    reader.beginObject()
    while (reader.hasNext()) {
      when (reader.selectName(options)) {
        0 -> {
          name = nullableStringAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 0).inv()
          mask0 = mask0 and 0xfffffffe.toInt()
        }
        1 -> {
          group = nullableStringAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 1).inv()
          mask0 = mask0 and 0xfffffffd.toInt()
        }
        2 -> version = nullableStringAdapter.fromJson(reader)
        -1 -> {
          // Unknown name, skip it.
          reader.skipName()
          reader.skipValue()
        }
      }
    }
    reader.endObject()
    @Suppress("UNCHECKED_CAST")
    val localConstructor: Constructor<Libraries.Library.ArtifactId> = this.constructorRef ?:
        Libraries.Library.ArtifactId::class.java.getDeclaredConstructor(String::class.java,
        String::class.java, String::class.java, Int::class.javaPrimitiveType,
        Util.DEFAULT_CONSTRUCTOR_MARKER).also { this.constructorRef = it }
    return localConstructor.newInstance(
        name,
        group,
        version,
        mask0,
        null
    )
  }

  override fun toJson(writer: JsonWriter, value: Libraries.Library.ArtifactId?) {
    if (value == null) {
      throw NullPointerException("value was null! Wrap in .nullSafe() to write nullable values.")
    }
    writer.beginObject()
    writer.name("name")
    nullableStringAdapter.toJson(writer, value.name)
    writer.name("group")
    nullableStringAdapter.toJson(writer, value.group)
    writer.name("version")
    nullableStringAdapter.toJson(writer, value.version)
    writer.endObject()
  }
}
