// Code generated by moshi-kotlin-codegen. Do not edit.
package de.michaelpohl.loopy.ui.licenses

import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import com.squareup.moshi.Moshi
import com.squareup.moshi.Types
import com.squareup.moshi.internal.Util
import java.lang.NullPointerException
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import kotlin.collections.emptySet
import kotlin.text.buildString

@Suppress("DEPRECATION", "unused", "ClassName", "REDUNDANT_PROJECTION")
class LibrariesJsonAdapter(
  moshi: Moshi
) : JsonAdapter<Libraries>() {
  private val options: JsonReader.Options = JsonReader.Options.of("libraries")

  private val listOfLibraryAdapter: JsonAdapter<List<Libraries.Library>> =
      moshi.adapter(Types.newParameterizedType(List::class.java, Libraries.Library::class.java),
      emptySet(), "libraries")

  override fun toString(): String = buildString(31) {
      append("GeneratedJsonAdapter(").append("Libraries").append(')') }

  override fun fromJson(reader: JsonReader): Libraries {
    var libraries: List<Libraries.Library>? = null
    reader.beginObject()
    while (reader.hasNext()) {
      when (reader.selectName(options)) {
        0 -> libraries = listOfLibraryAdapter.fromJson(reader) ?:
            throw Util.unexpectedNull("libraries", "libraries", reader)
        -1 -> {
          // Unknown name, skip it.
          reader.skipName()
          reader.skipValue()
        }
      }
    }
    reader.endObject()
    return Libraries(
        libraries = libraries ?: throw Util.missingProperty("libraries", "libraries", reader)
    )
  }

  override fun toJson(writer: JsonWriter, value: Libraries?) {
    if (value == null) {
      throw NullPointerException("value was null! Wrap in .nullSafe() to write nullable values.")
    }
    writer.beginObject()
    writer.name("libraries")
    listOfLibraryAdapter.toJson(writer, value.libraries)
    writer.endObject()
  }
}
