name: Build Loopy

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        id: checkout
        uses: actions/checkout@v2 
      - name: Expose version name
        uses: michpohl/android-expose-version-name-action@v1.0.0
        with:
          expose-version-name: 'true'
          expose-version-code: 'true'
      - name: Combine env vars
        uses: michpohl/action-concatenate-strings@v1.0.0
        with:
          first: ${{ env.ANDROID_VERSION_NAME }}
          second: ${{ github.run_number }}
          separator: '.'
          output-var-name: 'COMBINED_OUTPUT'
      - name: Set new version code and number
        uses: damienaicheh/update-android-version-gradle-action@v1.0.0
        with:
          build-gradle-path: app/build.gradle
          version-code: ${{ github.run_number }}
          version-name: '${{ env.COMBINED_OUTPUT }}'
          print-file: 'true'
      - name: Build the app
        id: build
        run: ./gradlew build
      - name: Sign app APK
        uses: r0adkll/sign-android-release@v1
        id: sign
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          alias: ${{ secrets.KS_A }}
          keyStorePassword: ${{ secrets.KS_PW }}
          keyPassword: ${{ secrets.KS_PR_PW }}
      - name: Deploy to Google
        id: deploy
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.michaelpohl.loopyplayer2
          releaseFiles: app/build/outputs/apk/release/app-release-unsigned-signed.apk
          track: production
          # inAppUpdatePriority: 2
          # userFraction: 1
          # whatsNewDirectory: distribution/whatsnew
