name: Build Loopy

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        id: checkout
        uses: actions/checkout@v2 
      - name: Build the app
        id: build
        run: ./gradlew build
      - name: Sign app APK
        uses: r0adkll/sign-android-release@v1
        id: sign
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          alias: ${{ secrets.KS_A }}
          keyStorePassword: ${{ secrets.KS_PW }}
          keyPassword: ${{ secrets.KS_PR_PW }}
      - name: Deploy to Google
        id: deploy
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.michaelpohl.loopyplayer2
          releaseFiles: app/build/outputs/apk/release/app-release-unsigned-signed.apk
          track: alpha
          # inAppUpdatePriority: 2
          # userFraction: 1
          # whatsNewDirectory: distribution/whatsnew
